#!/bin/bash
# sum3  按列计算和
# input 多行数字
# output    每列的综合，输出为一行
# 缺少的字段默认为0

function isnum(n) {return n ~ /^[+-]?[0-9]+$/}

NR == 1 {nfld = NF
        for ( i = 1; i <= NF; i++)
        {
            numcol[i] = isnum($i)
        }}
{for (i = 1; i<= NF; i++){
   if (numcol[i]){
        sum[i] += $i
   }
}} END {
    for (i = 1; i <= nfld;i++){
        if (numcol[i]){
            printf("%g",sum[i])
        }else{
            printf("--")
        }

        if(i<nfld){
            printf("\t")
        }else{
            printf("\n")
        }
    }
}
